services:
  
# LAS-NoCode-Rule-Editor                
  editor:
    build:
      context: ./editor
    container_name: editor
    hostname: editor
    restart: always
    volumes:
      - ./editor:/app
      - ./editor/flow.db:/app/flow.db
    ports:
      - "5000:5000"